### ISSUE TITLE
Kişi classı

### ISSUE THREAD

**Issue by mesutozturk** [mesutozturk/GitHubTestWM6#1]
Kişi classının tanımlanması ve validasyonların hazırlanması

**Comment by nillabobillababolla** [comment]
@mesutozturk Tamamlandı.

**Comment by mesutozturk** [comment]
@aysenurka validasyonları kontrol eder misin?

**Comment by aysenurka** [comment]
@mesutozturk düzenlenme yapıldı

**Comment by mesutozturk** [comment]
👍
